apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spinnaker-app
  namespace: argocd
spec:
  source:
    path: deploy/spinnaker/docker-local
    repoURL: https://github.com/xRegner/spinnaker-operator-docker-desktop.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spinnaker-operator
  project: default